# Generated by Django 3.1 on 2021-12-20 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomAnomalie', models.CharField(max_length=100)),
                ('descriptionAnomalie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('localisation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomServ', models.CharField(max_length=50)),
                ('descriptionService', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomRessource', models.CharField(max_length=50)),
                ('descriptionRes', models.CharField(max_length=200)),
                ('creer_le', models.DateTimeField(auto_now_add=True)),
                ('modifier_le', models.DateTimeField(auto_now_add=True)),
                ('localisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources.localisation')),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ressources.service')),
            ],
        ),
        migrations.CreateModel(
            name='AnomalieRessource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_present', models.BooleanField()),
                ('detecter_le', models.DateTimeField(auto_now_add=True)),
                ('corriger_le', models.DateTimeField(auto_now_add=True)),
                ('anomalie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources.anomalie')),
                ('localisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources.localisation')),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources.ressource')),
            ],
        ),
    ]
