# Generated by Django 3.1 on 2021-12-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='respnsables',
            new_name='responsables',
        ),
    ]
