# Generated by Django 3.1 on 2021-12-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomalieressource',
            name='est_present',
        ),
        migrations.AddField(
            model_name='anomalieressource',
            name='etat',
            field=models.CharField(blank=True, choices=[('present', 'present'), ('En cours de traitement', 'En cours de traitement'), ('terminé', 'terminé')], default='present', max_length=30),
        ),
        migrations.AddField(
            model_name='anomalieressource',
            name='nombreSignalement',
            field=models.IntegerField(default=0, max_length=200),
        ),
    ]
