# Generated by Django 3.1 on 2021-12-15 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ressources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomalieressource',
            name='anomalie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources.anomalie'),
        ),
        migrations.AddField(
            model_name='anomalieressource',
            name='localisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources.localisation'),
        ),
        migrations.AddField(
            model_name='anomalieressource',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources.ressource'),
        ),
    ]
