# Generated by Django 3.1 on 2021-12-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0002_auto_20211226_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalieressource',
            name='nombreSignalement',
            field=models.IntegerField(default=0),
        ),
    ]
